apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-dec18-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot-dec18-1:415cb11a0c032725e61c89bfd6a12cee5599db99@sha256:1d05a3d7b0571dae395d3f0804bd45649c7f5e22d40e65f58a74b00a045a3b35 # use pre-built to bootstrap 
          name: app-inference
